# Generated by Django 3.1.1 on 2020-10-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200930_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='criado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='publicado',
            new_name='published',
        ),
    ]
